# Generated by Django 5.2.5 on 2025-08-09 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('category', models.CharField(choices=[('retail', 'Retail'), ('restaurant', 'Restaurant'), ('hospitality', 'Hospitality'), ('beauty', 'Beauty & Wellness'), ('entertainment', 'Entertainment'), ('travel', 'Travel'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('point_value', models.DecimalField(decimal_places=2, default=0.01, help_text='Monetary value of a single point (e.g., 0.01 = 1 cent per point)', max_digits=10)),
                ('points_per_currency', models.IntegerField(default=1, help_text='Points awarded per unit of currency spent')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='BusinessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#007BFF', help_text='Hex code for primary color', max_length=7)),
                ('secondary_color', models.CharField(default='#6C757D', help_text='Hex code for secondary color', max_length=7)),
                ('accent_color', models.CharField(default='#FFC107', help_text='Hex code for accent color', max_length=7)),
                ('enable_point_expiry', models.BooleanField(default=False)),
                ('point_expiry_days', models.IntegerField(default=365, help_text='Days until points expire')),
                ('enable_cross_business_redemption', models.BooleanField(default=True)),
                ('cross_business_conversion_rate', models.DecimalField(decimal_places=2, default=1.0, help_text='Conversion rate for points from other businesses', max_digits=5)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='tenants.business')),
            ],
        ),
    ]
